from __future__ import annotations

from wargames.evaluation.schema import GameRewardSchema, RewardField, RewardPrimitiveSpec

OPENSURGE_REWARD_SCHEMA = GameRewardSchema(
    game="opensurge",
    world_type="wargames.games.opensurge.world.OpenSurgeWorld",
    tick_rate=60,
    fields={
        "tick": RewardField("tick", "int", "track", "WarGames step tick."),
        "mission.finished": RewardField("mission.finished", "bool", "maximize", "Act cleared."),
        "mission.failed": RewardField("mission.failed", "bool", "minimize", "Player death or runtime failure."),
        "level.file": RewardField("level.file", "str", "track", "Level file path."),
        "level.name": RewardField("level.name", "str", "track", "Level display name."),
        "level.act": RewardField("level.act", "int", "track", "Level act number."),
        "level.elapsed_ticks": RewardField("level.elapsed_ticks", "int", "minimize", "Elapsed level ticks."),
        "level.elapsed_seconds": RewardField("level.elapsed_seconds", "float", "minimize", "Elapsed level seconds."),
        "level.width": RewardField("level.width", "float", "track", "Level width."),
        "level.height": RewardField("level.height", "float", "track", "Level height."),
        "player.x": RewardField("player.x", "float | None", "track", "Player x position."),
        "player.y": RewardField("player.y", "float | None", "track", "Player y position."),
        "player.xsp": RewardField("player.xsp", "float | None", "maximize", "Horizontal speed."),
        "player.ysp": RewardField("player.ysp", "float | None", "track", "Vertical speed."),
        "player.gsp": RewardField("player.gsp", "float | None", "track", "Ground speed."),
        "player.speed": RewardField("player.speed", "float | None", "maximize", "Player speed."),
        "player.rings": RewardField("player.rings", "int", "maximize", "Collected rings."),
        "player.score": RewardField("player.score", "int", "maximize", "Score."),
        "player.lives": RewardField("player.lives", "int", "maximize", "Remaining lives."),
        "player.alive": RewardField("player.alive", "bool", "maximize", "Player is alive."),
        "player.dying": RewardField("player.dying", "bool", "minimize", "Player is dying."),
        "player.winning": RewardField("player.winning", "bool", "maximize", "Player is in the clear sequence."),
        "player.rolling": RewardField("player.rolling", "bool", "track", "Player is rolling."),
        "player.jumping": RewardField("player.jumping", "bool", "track", "Player is jumping."),
    },
    primitives={
        "terminal": RewardPrimitiveSpec(
            "terminal",
            ("mission.finished", "mission.failed"),
            1.0,
            "terminal",
            "Success/failure outcome.",
        ),
        "delta_rings": RewardPrimitiveSpec(
            "delta_rings",
            ("player.rings",),
            1.0,
            "per_step",
            "Reward newly collected rings.",
        ),
        "delta_score": RewardPrimitiveSpec(
            "delta_score",
            ("player.score",),
            1.0,
            "per_step",
            "Reward score increases.",
        ),
        "progress_x": RewardPrimitiveSpec(
            "progress_x",
            ("player.x",),
            1.0,
            "per_step",
            "Reward forward horizontal progress.",
        ),
        "speed": RewardPrimitiveSpec(
            "speed",
            ("player.speed",),
            1.0,
            "per_step",
            "Reward moving quickly.",
        ),
        "death_penalty": RewardPrimitiveSpec(
            "death_penalty",
            ("player.dying",),
            1.0,
            "per_step",
            "Penalty when the player dies.",
        ),
        "time_penalty": RewardPrimitiveSpec(
            "time_penalty",
            ("tick",),
            1.0,
            "per_step",
            "Small pressure to finish efficiently.",
        ),
    },
)
